ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS remote_id VARCHAR(80),
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE project_members
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE acts
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE characters
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS image_remote_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS image_checksum VARCHAR(128);

ALTER TABLE locations
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE scenes
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

ALTER TABLE scene_characters
    ADD COLUMN IF NOT EXISTS client_uuid UUID,
    ADD COLUMN IF NOT EXISTS server_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

UPDATE projects
SET client_uuid = md5('PROJECT:' || id)::uuid
WHERE client_uuid IS NULL;

UPDATE project_members
SET client_uuid = md5('PROJECT_MEMBER:' || project_id || ':' || user_id)::uuid
WHERE client_uuid IS NULL;

UPDATE acts
SET client_uuid = md5('ACT:' || id)::uuid
WHERE client_uuid IS NULL;

UPDATE characters
SET client_uuid = md5('CHARACTER:' || id)::uuid
WHERE client_uuid IS NULL;

UPDATE locations
SET client_uuid = md5('STORY_LOCATION:' || id)::uuid
WHERE client_uuid IS NULL;

UPDATE scenes
SET client_uuid = md5('SCENE:' || id)::uuid
WHERE client_uuid IS NULL;

UPDATE scene_characters
SET client_uuid = md5('SCENE_CHARACTER:' || scene_id || ':' || character_id)::uuid
WHERE client_uuid IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_projects_client_uuid ON projects(client_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_project_members_client_uuid ON project_members(client_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_acts_client_uuid ON acts(client_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_characters_client_uuid ON characters(client_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_locations_client_uuid ON locations(client_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_scenes_client_uuid ON scenes(client_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_scene_characters_client_uuid ON scene_characters(client_uuid);

CREATE INDEX IF NOT EXISTS ix_projects_sync ON projects(owner_id, server_version, updated_at);
CREATE INDEX IF NOT EXISTS ix_acts_sync ON acts(project_id, server_version, updated_at);
CREATE INDEX IF NOT EXISTS ix_characters_sync ON characters(project_id, server_version, updated_at);
CREATE INDEX IF NOT EXISTS ix_locations_sync ON locations(project_id, server_version, updated_at);
CREATE INDEX IF NOT EXISTS ix_scenes_sync ON scenes(project_id, server_version, updated_at);

CREATE TABLE IF NOT EXISTS sync_idempotency (
    idempotency_key UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id UUID NOT NULL,
    operation VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    response_json TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sync_idempotency_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS sync_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cursor_value VARCHAR(80) NOT NULL UNIQUE,
    project_id BIGINT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id UUID NOT NULL,
    operation VARCHAR(30) NOT NULL,
    server_version BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sync_change_log_project FOREIGN KEY(project_id) REFERENCES projects(id)
);

CREATE INDEX IF NOT EXISTS ix_sync_change_log_project_id ON sync_change_log(project_id, id);
CREATE INDEX IF NOT EXISTS ix_sync_change_log_cursor ON sync_change_log(cursor_value);

CREATE TABLE IF NOT EXISTS file_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NULL,
    client_uuid UUID NOT NULL UNIQUE,
    entity_type VARCHAR(80) NULL,
    entity_id UUID NULL,
    remote_url VARCHAR(500) NOT NULL,
    checksum VARCHAR(128) NULL,
    mime_type VARCHAR(120) NULL,
    file_size BIGINT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_file_assets_project FOREIGN KEY(project_id) REFERENCES projects(id),
    CONSTRAINT fk_file_assets_created_by FOREIGN KEY(created_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS ix_file_assets_project ON file_assets(project_id);
