CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    system_role VARCHAR(30) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    genre VARCHAR(100) NULL,
    description TEXT NULL,
    start_date DATE NULL,
    poster_url VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NULL,
    CONSTRAINT fk_projects_owner FOREIGN KEY(owner_id) REFERENCES users(id)
);

CREATE TABLE project_members (
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    PRIMARY KEY(project_id, user_id),
    CONSTRAINT fk_project_members_project FOREIGN KEY(project_id) REFERENCES projects(id),
    CONSTRAINT fk_project_members_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE acts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    sequence_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_acts_project FOREIGN KEY(project_id) REFERENCES projects(id),
    CONSTRAINT uq_acts_project_order UNIQUE(project_id, sequence_order),
    CONSTRAINT ck_acts_sequence_order CHECK(sequence_order >= 1)
);

CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    role_type VARCHAR(30) NOT NULL,
    description TEXT NULL,
    image_url VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_characters_project FOREIGN KEY(project_id) REFERENCES projects(id)
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    setting_type VARCHAR(10) NOT NULL,
    time_of_day VARCHAR(10) NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_locations_project FOREIGN KEY(project_id) REFERENCES projects(id)
);

CREATE TABLE scenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    act_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    scene_number INT NOT NULL,
    title VARCHAR(200) NULL,
    summary TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    estimated_minutes INT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_scenes_project FOREIGN KEY(project_id) REFERENCES projects(id),
    CONSTRAINT fk_scenes_act FOREIGN KEY(act_id) REFERENCES acts(id),
    CONSTRAINT fk_scenes_location FOREIGN KEY(location_id) REFERENCES locations(id),
    CONSTRAINT uq_scenes_project_number UNIQUE(project_id, scene_number),
    CONSTRAINT ck_scenes_scene_number CHECK(scene_number >= 1),
    CONSTRAINT ck_scenes_estimated_minutes CHECK(estimated_minutes IS NULL OR estimated_minutes > 0)
);

CREATE TABLE scene_characters (
    scene_id BIGINT NOT NULL,
    character_id BIGINT NOT NULL,
    PRIMARY KEY(scene_id, character_id),
    CONSTRAINT fk_scene_characters_scene FOREIGN KEY(scene_id) REFERENCES scenes(id) ON DELETE CASCADE,
    CONSTRAINT fk_scene_characters_character FOREIGN KEY(character_id) REFERENCES characters(id) ON DELETE CASCADE
);

CREATE INDEX ix_projects_owner_id ON projects(owner_id);
CREATE INDEX ix_project_members_user_id ON project_members(user_id);
CREATE INDEX ix_acts_project_id ON acts(project_id);
CREATE INDEX ix_characters_project_id ON characters(project_id);
CREATE INDEX ix_locations_project_id ON locations(project_id);
CREATE INDEX ix_scenes_project_id ON scenes(project_id);
CREATE INDEX ix_scenes_act_id ON scenes(act_id);
CREATE INDEX ix_scenes_location_id ON scenes(location_id);
CREATE INDEX ix_scenes_status ON scenes(status);
CREATE INDEX ix_scene_characters_character_id ON scene_characters(character_id);
